FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY FilmApiSeeder/FilmApiSeeder.csproj ./FilmApiSeeder/
COPY FilmAPI.csproj ./
RUN dotnet restore FilmApiSeeder/FilmApiSeeder.csproj
COPY . .
RUN dotnet publish FilmApiSeeder/FilmApiSeeder.csproj -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "FilmApiSeeder.dll"]
