// <auto-generated />
using System;
using FilmAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmAPI.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    [Migration("20260512082922_Iteration5_1_Ecommerce")]
    partial class Iteration5_1_Ecommerce
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FilmAPI.Model.AccountActionToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UtenteId");

                    b.ToTable("AccountActionTokens");
                });

            modelBuilder.Entity("FilmAPI.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CartType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GuestToken")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RinnoviResidui")
                        .HasColumnType("int");

                    b.Property<decimal>("ScontoCoupon")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Subtotale")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Totale")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("GuestToken", "Stato");

                    b.HasIndex("UtenteId", "Stato");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("FilmAPI.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DettaglioJson")
                        .HasColumnType("longtext");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("FilmAPI.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descrizione = "Film fantasy",
                            Nome = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Descrizione = "Film horror",
                            Nome = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Descrizione = "Film drammatici",
                            Nome = "Drammatico"
                        },
                        new
                        {
                            Id = 4,
                            Descrizione = "Film commedia",
                            Nome = "Commedia"
                        },
                        new
                        {
                            Id = 5,
                            Descrizione = "Film d'azione",
                            Nome = "Azione"
                        },
                        new
                        {
                            Id = 6,
                            Descrizione = "Film thriller",
                            Nome = "Thriller"
                        });
                });

            modelBuilder.Entity("FilmAPI.Model.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Capienza")
                        .HasColumnType("int");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodiceLocale")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitudine")
                        .HasColumnType("double");

                    b.Property<double?>("Longitudine")
                        .HasColumnType("double");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CodiceLocale")
                        .IsUnique();

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("FilmAPI.Model.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxPerUtente")
                        .HasColumnType("int");

                    b.Property<int>("MaxUtilizzi")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinImportoCarrello")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuantitaMinima")
                        .HasColumnType("int");

                    b.Property<decimal?>("ScontoMassimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Stackable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TipoSconto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoTarget")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilizziAttuali")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidoAl")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidoDal")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValoreSconto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("FilmAPI.Model.CouponUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ScontoApplicato")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("UtenteId");

                    b.HasIndex("CouponId", "UtenteId", "CartId")
                        .IsUnique();

                    b.ToTable("CouponUsages");
                });

            modelBuilder.Entity("FilmAPI.Model.ExternalAuthExchangeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("ExternalAuthExchangeCodes");
                });

            modelBuilder.Entity("FilmAPI.Model.ExternalAuthState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mode")
                        .HasColumnType("longtext");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReturnUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExternalAuthStates");
                });

            modelBuilder.Entity("FilmAPI.Model.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackdropPath")
                        .HasColumnType("longtext");

                    b.Property<string>("CastPrincipale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CopertinaPath")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataProduzione")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUscita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescrizioneLunga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<string>("FilmatoPath")
                        .HasColumnType("longtext");

                    b.Property<int>("RegistaId")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitoloOriginale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TmdbMovieId")
                        .HasColumnType("int");

                    b.Property<string>("TmdbSyncStato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimaSyncTmdbUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RegistaId");

                    b.HasIndex("TmdbMovieId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("FilmAPI.Model.FilmCategoria", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("FilmId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("FilmCategorie");
                });

            modelBuilder.Entity("FilmAPI.Model.GiftCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailDestinatario")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ImportoIniziale")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Messaggio")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SaldoResiduo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("Scadenza")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtenteAcquirenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.HasIndex("UtenteAcquirenteId");

                    b.ToTable("GiftCards");
                });

            modelBuilder.Entity("FilmAPI.Model.GiftCardTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImmaginePath")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GiftCardTemplates");
                });

            modelBuilder.Entity("FilmAPI.Model.GiftCardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GiftCardId")
                        .HasColumnType("int");

                    b.Property<decimal>("Importo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoDopo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("GiftCardId");

                    b.ToTable("GiftCardTransactions");
                });

            modelBuilder.Entity("FilmAPI.Model.InventoryReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("InventoryReservations");
                });

            modelBuilder.Entity("FilmAPI.Model.NotificationSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimoInvio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("NotificationSubscriptions");
                });

            modelBuilder.Entity("FilmAPI.Model.Prenotazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("CinemaValidazioneId")
                        .HasColumnType("int");

                    b.Property<string>("CodiceAcquisto")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ImportoCartaUsato")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NumeroPosti")
                        .HasColumnType("int");

                    b.Property<string>("PostiSelezionati")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProiezioneId")
                        .HasColumnType("int");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("TotalePrezzo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.Property<bool>("Validato")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ValidatoAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ValidatoDaUtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("CodiceAcquisto")
                        .IsUnique();

                    b.HasIndex("ProiezioneId");

                    b.HasIndex("StripeSessionId")
                        .IsUnique();

                    b.HasIndex("UtenteId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("FilmAPI.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImmaginePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrezzoBase")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("FilmAPI.Model.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrezzoExtra")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("FilmAPI.Model.Proiezione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ora")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrezzoBase")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("SalaId", "Data", "Ora")
                        .IsUnique();

                    b.HasIndex("CinemaId", "FilmId", "Data", "Ora");

                    b.ToTable("Proiezioni");
                });

            modelBuilder.Entity("FilmAPI.Model.Regista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nazionalita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Registi");
                });

            modelBuilder.Entity("FilmAPI.Model.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("MappaPostiJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroFile")
                        .HasColumnType("int");

                    b.Property<int>("NumeroProgressivo")
                        .HasColumnType("int");

                    b.Property<int>("PostiPerFila")
                        .HasColumnType("int");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId", "NumeroProgressivo")
                        .IsUnique();

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("FilmAPI.Model.SeatLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PostoCodice")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ProiezioneId")
                        .HasColumnType("int");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("UtenteId");

                    b.HasIndex("ProiezioneId", "PostoCodice")
                        .IsUnique();

                    b.ToTable("SeatLocks");
                });

            modelBuilder.Entity("FilmAPI.Model.UserExternalLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenantId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.HasIndex("Provider", "TenantId", "ProviderKey");

                    b.ToTable("UserExternalLogins");
                });

            modelBuilder.Entity("FilmAPI.Model.UserSecurityAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Provider")
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<int?>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EventType", "CreatedAtUtc");

                    b.HasIndex("UtenteId", "CreatedAtUtc");

                    b.ToTable("UserSecurityAuditLogs");
                });

            modelBuilder.Entity("FilmAPI.Model.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthVersion")
                        .HasColumnType("int");

                    b.Property<int?>("CinemaPreferitoId")
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CreditoPiattaforma")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastLoginProvider")
                        .HasColumnType("longtext");

                    b.Property<bool>("LocalCredentialsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("Ruolo");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("FilmAPI.Model.AccountActionToken", b =>
                {
                    b.HasOne("FilmAPI.Model.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("FilmAPI.Model.Cart", b =>
                {
                    b.HasOne("FilmAPI.Model.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FilmAPI.Model.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coupon");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("FilmAPI.Model.CartItem", b =>
                {
                    b.HasOne("FilmAPI.Model.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("FilmAPI.Model.CouponUsage", b =>
                {
                    b.HasOne("FilmAPI.Model.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Coupon", "Coupon")
                        .WithMany("Utilizzi")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Coupon");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("FilmAPI.Model.Film", b =>
                {
                    b.HasOne("FilmAPI.Model.Regista", "Regista")
                        .WithMany("Films")
                        .HasForeignKey("RegistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regista");
                });

            modelBuilder.Entity("FilmAPI.Model.FilmCategoria", b =>
                {
                    b.HasOne("FilmAPI.Model.Categoria", "Categoria")
                        .WithMany("FilmCategorie")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany("FilmCategorie")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("FilmAPI.Model.GiftCard", b =>
                {
                    b.HasOne("FilmAPI.Model.Utente", "UtenteAcquirente")
                        .WithMany()
                        .HasForeignKey("UtenteAcquirenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtenteAcquirente");
                });

            modelBuilder.Entity("FilmAPI.Model.GiftCardTransaction", b =>
                {
                    b.HasOne("FilmAPI.Model.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FilmAPI.Model.GiftCard", "GiftCard")
                        .WithMany("Transazioni")
                        .HasForeignKey("GiftCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("GiftCard");
                });

            modelBuilder.Entity("FilmAPI.Model.InventoryReservation", b =>
                {
                    b.HasOne("FilmAPI.Model.Cart", "Cart")
                        .WithMany("InventoryReservations")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("FilmAPI.Model.NotificationSubscription", b =>
                {
                    b.HasOne("FilmAPI.Model.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("FilmAPI.Model.Prenotazione", b =>
                {
                    b.HasOne("FilmAPI.Model.Cart", "Cart")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FilmAPI.Model.Proiezione", "Proiezione")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("ProiezioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Utente", "Utente")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Proiezione");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("FilmAPI.Model.ProductVariant", b =>
                {
                    b.HasOne("FilmAPI.Model.Product", "Product")
                        .WithMany("Varianti")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FilmAPI.Model.Proiezione", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany("Proiezioni")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany("Proiezioni")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Sala", "Sala")
                        .WithMany("Proiezioni")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cinema");

                    b.Navigation("Film");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("FilmAPI.Model.Sala", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany("Sale")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("FilmAPI.Model.SeatLock", b =>
                {
                    b.HasOne("FilmAPI.Model.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FilmAPI.Model.Proiezione", "Proiezione")
                        .WithMany()
                        .HasForeignKey("ProiezioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Proiezione");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("FilmAPI.Model.UserExternalLogin", b =>
                {
                    b.HasOne("FilmAPI.Model.Utente", "Utente")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("FilmAPI.Model.UserSecurityAuditLog", b =>
                {
                    b.HasOne("FilmAPI.Model.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("FilmAPI.Model.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("InventoryReservations");

                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("FilmAPI.Model.Categoria", b =>
                {
                    b.Navigation("FilmCategorie");
                });

            modelBuilder.Entity("FilmAPI.Model.Cinema", b =>
                {
                    b.Navigation("Proiezioni");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("FilmAPI.Model.Coupon", b =>
                {
                    b.Navigation("Utilizzi");
                });

            modelBuilder.Entity("FilmAPI.Model.Film", b =>
                {
                    b.Navigation("FilmCategorie");

                    b.Navigation("Proiezioni");
                });

            modelBuilder.Entity("FilmAPI.Model.GiftCard", b =>
                {
                    b.Navigation("Transazioni");
                });

            modelBuilder.Entity("FilmAPI.Model.Product", b =>
                {
                    b.Navigation("Varianti");
                });

            modelBuilder.Entity("FilmAPI.Model.Proiezione", b =>
                {
                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("FilmAPI.Model.Regista", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("FilmAPI.Model.Sala", b =>
                {
                    b.Navigation("Proiezioni");
                });

            modelBuilder.Entity("FilmAPI.Model.Utente", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("Prenotazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
